name: NeoChatMod
author: Neoblade298
main: me.neoblade298.neochatmod.ChatMod
api-version: 1.14
version: 1.0
softdepend: [TownyChat]
commands:
   servermute:
      description: Does its job
      usage: /servermute